chore: add logic to do multiple eas updates.

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -3,7 +3,7 @@ on:
   workflow_dispatch:
     inputs:
       version:
-        description: 'Version number (for app.json). Eg: 1.1.7'
+        description: 'Release (Major-Minor) Version number (for app.json). Eg: 1.2'
         required: false
         type: string
 
@@ -19,51 +19,60 @@ jobs:
           cache: yarn
           cache-dependency-path: '**/yarn.lock'
 
-      - name: Print version strings
-        run: |
-          CURRENT_APP_JSON_VERSION=$(jq -r '.expo.version' app.json)
-          USER_SUPPLIED_APP_JSON_VERSION=${{ github.event.inputs.version }}
-          echo "Current App version: ${CURRENT_APP_JSON_VERSION}; You entered: ${USER_SUPPLIED_APP_JSON_VERSION}"
+      # - name: Install dependencies
+      #   run: yarn install
 
-      - name: Allow difference only in PATCH version in the supplied version string
-        if: github.event.inputs.version
+      # - name: Setup Expo and EAS
+      #   uses: expo/expo-github-action@v8
+      #   with:
+      #     eas-version: latest
+      #     token: ${{ secrets.EXPO_TOKEN }}
+
+
+      - name: (Major-Minor Release supplied) eas update flow
+        if: ${{ github.event.inputs.version }}
         run: |
+          # Ensure that the major.minor version is the same
           CURRENT_APP_JSON_VERSION=$(jq -r '.expo.version' app.json)
           MAJOR_MINOR=${CURRENT_APP_JSON_VERSION%.*}
-          VERSION=${{ github.event.inputs.version }}
+          RELEASE="${{ github.event.inputs.version }}"
+          echo "Current App version: ${CURRENT_APP_JSON_VERSION}; You entered: ${RELEASE}"
           
-          if [[ ! "$VERSION" =~ ^"${MAJOR_MINOR}" ]]; then
-            echo "Invalid supplied app version: ${VERSION}. Only ${MAJOR_MINOR}.X versions are allowed."
+          if [[ "${RELEASE}" != "${MAJOR_MINOR}" ]]; then
+            echo "Invalid supplied app release version: ${RELEASE}. Expected: ${MAJOR_MINOR}."
             exit 1
           fi
 
-      - name: Install dependencies
-        run: yarn install
+          # get all the patch releases for this major-minor release
+          RELEASES_JSON_FILE="src/app.json"
+          PATCHES_KEY=".releases.\"release-${RELEASE}\""
+          PATCHES_VAL=$( jq -r "${PATCHES_KEY}[]" "${RELEASES_JSON_FILE}" 2>/dev/null)
 
-      - name: Setup Expo and EAS
-        uses: expo/expo-github-action@v8
-        with:
-          eas-version: latest
-          token: ${{ secrets.EXPO_TOKEN }}
-
-      - name: Update app.json (if supplied version is different)
-        if: github.event.inputs.version
-        run: |
-          CURRENT_APP_JSON_VERSION=$(jq -r '.expo.version' app.json)
-          VERSION=${{ github.event.inputs.version }}
-
-          if [[ "${CURRENT_APP_JSON_VERSION}" != "${VERSION}" ]]; then
-            echo "Detected a different app.json version. Updating app.json..."
-            jq --arg version "$VERSION" '.expo.version = $version' app.json > app.temp.json
-            mv app.temp.json app.json
-          else
-            echo "app.json version is unchanged"
+          if [[ -z "$PATCHES_VAL" ]]; then
+            echo "No patch releases found for release: ${RELEASE}"
+            exit 1
           fi
 
-      - name: Print current version in app.json
+          for PATCH_RELEASE in ${PATCHES_VAL}; do
+            # update app.json
+            jq --arg version "${PATCH_RELEASE}" '.expo.version = $version' app.json > app.temp.json
+            mv app.temp.json app.json
+
+            # display app.json version
+            EAS_UPDATE_APP_JSON_VERSION=$(jq -r '.expo.version' app.json)
+            echo "app.json version before eas update is = ${EAS_UPDATE_APP_JSON_VERSION}"
+
+            # perform eas update
+            echo "Performing eas update for version: ${PATCH_RELEASE}"
+
+            # update the source maps
+            echo "Updating sourcemap for version: ${PATCH_RELEASE}"
+          done
+
+      - name: (Default - no version supplied) eas update flow
+        if: ${{ !github.event.inputs.version}}
         run: |
+          # display app version before update
           EAS_UPDATE_APP_JSON_VERSION=$(jq -r '.expo.version' app.json)
           echo "app.json version before eas update is = ${EAS_UPDATE_APP_JSON_VERSION}"
-
-      - name: Perform eas update (workflow dispatch)
-        run: NODE_OPTIONS="--max-old-space-size=8192" eas update --channel=production --message="$(git log -1 --pretty=%B)"
+          NODE_OPTIONS="--max-old-space-size=8192" eas update --channel=production --message="$(git log -1 --pretty=%B)"
